name: web_scraping
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- asn1crypto=0.22.0=py36_0
- attrs=17.2.0=py36_0
- automat=0.6.0=py36_0
- beautifulsoup4=4.5.3=py36_0
- bleach=1.5.0=py36_0
- ca-certificates=2017.4.17=0
- certifi=2017.4.17=py36_0
- cffi=1.10.0=py36_0
- chardet=3.0.2=py36_1
- cryptography=1.9=py36_0
- decorator=4.1.1=py36_0
- entrypoints=0.2.3=py36_1
- html5lib=0.9999999=py36_0
- hypothesis=3.11.6=py36_0
- icu=58.1=1
- idna=2.5=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- jinja2=2.9.5=py36_0
- jsonschema=2.5.1=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libffi=3.2.1=3
- libiconv=1.14=4
- libsodium=1.0.10=0
- libxml2=2.9.4=4
- libxslt=1.1.29=5
- lxml=3.8.0=py36_0
- markupsafe=1.0=py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.2.1=py36_1
- nbformat=4.3.0=py36_0
- ncurses=5.9=10
- notebook=5.0.0=py36_0
- openssl=1.0.2l=0
- pandas=0.20.3=py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.3=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.2=py36_0
- pyasn1=0.2.3=py36_0
- pyasn1-modules=0.0.9=py36_0
- pycparser=2.18=py36_0
- pydispatcher=2.0.5=py36_0
- pygments=2.2.0=py36_0
- pympler=0.5=py36_0
- pyopenssl=16.2.0=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_2
- readline=6.2=0
- requests=2.18.1=py36_0
- scrapy=1.4.0=py36_0
- selenium=3.4.3=py36_0
- setuptools=36.2.2=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.10.0=py36_1
- sqlalchemy=1.1.11=py36_0
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.19=1
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- urllib3=1.21.1=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.2=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- constantly=15.1.0=py36_0
- cssselect=1.0.1=py36_0
- hyperlink=17.1.1=py36_0
- incremental=16.10.1=py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- parsel=1.2.0=py36_0
- pymongo=3.4.0=py36_0
- queuelib=1.4.2=py36_0
- service_identity=17.0.0=py36_0
- twisted=17.5.0=py36_0
- w3lib=1.17.0=py36_0
- zope=1.0=py36_0
- zope.interface=4.4.2=py36_0
- pip:
  - ipynb==0.4
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - service-identity==17.0.0
prefix: /Users/tbrooks/anaconda/envs/web_scraping

